eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8762
spring:
  application:
    name: eurekaclient
#   rabbitmq:
#     host: localhost
#     port: 5672
#     username: guest
#     password: guest
#   sleuth:
#     sampler:
#       percentage: 1.0
management:
  security:
    enabled: false  #关闭安全验证，否则访问refresh端点时会提示权限不足
